import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "../components/navbar/navbar";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./Providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<NavbarComponent />
					{children}
				</Providers>
			</body>
		</html>
	);
}
